### ISSUE TITLE
Which repository is the right one?

### ISSUE THREAD

**Issue by mahbobyosf** [twfekkiki/FlutterPayfort#1]
Hello twfekkiki,

You have published two Payfort Flutter repositories, which is the right one.
and how can I contact you.

Best regards

**Comment by twfekkiki** [comment]
Hello Mhbob.

This is the last repository : https://github.com/twfekkiki/FlutterPayfort

But you should know that this package is still under development and not
tested well, and you should also know that I have implemented the Android
platform only.

And Please notice that you should include the FortSDK module manually to
your android project.

I hope my code helps you.

BestRegards

**Comment by mahbobyosf** [comment]
Thank you very much
